services:
  - type: web
    name: yemen-net-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY_B64
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000